### ISSUE TITLE
Thanks and some suggestions

### ISSUE THREAD

**Issue by tnt** [gphalkes/tilde#7] opened 2016-04-05 16:24 UTC
Hello,

I'm using tilde now for about to weeks when needing to edit something in the shell (I had never heard of it before) and am very pleased about its existence. Thank you very much!

I think it definitely deserves to be included regularly in all Linux distributions. Until then - surely rather a matter of months than years - it is very nice to can use your package-repositories. Thank you also for these additional efforts that make the installation very convenient.

Though it is absolutely sufficient for my purposes there are some features that would be luxury to have:
- more language modes (Ruby, Elixir, ..)
- a fallback encoding (settable or just iso-8859-1?) 
- recognition of file types by Emacs and Vim mode-lines like `#-*- mode: shell-script;-*-` (also for setting the encoding?)
- multiline regex replace

Best regards, T.

**Comment by clhess** [comment] 2016-09-08 15:51
Yes, this is a very nice, quick text editor.

Couple more suggestions...
- add command line options to set the line & column to open a file at
- add ctag support

I'm sure there are plenty of these types of requests.  I may just try to pull the source and see if I can get it to compile and add these in myself sometime.

**Comment by tnt** [comment] 2016-09-21 10:17
A real show stopper is that is doesn't detect a `ssh` session or at least behaves the same as it run locally. In `ssh` sessions it should not replace the selection with its own. It is alas impossible to copy text from a remote session in a terminal.

**Comment by gphalkes** [comment] 2016-09-28 06:17
Thanks for your comments, and apologies for not responding sooner. I unfortunately don't have much time to develop on tilde at the moment, so new features will be slow to appear. I'm happy to apply changes by others though.

As for copying on ssh sessions: I'm not entirely sure from your description what the problem is you're facing. I will add that copying between tilde and other programs (ab)uses the X clipboard. Hence, if you run tilde in an ssh session without enabling X forwarding, it can't use the X clipboard, and will only do in-program copy-paste. However, depending on the round-trip time on the connection to the remote computer, this may slow down tilde when selecting text as it has to update the selection often in that case.

**Comment by gphalkes** [comment] 2016-09-28 06:38
One more comment: tilde should have support for emacs/vim mode-lines. However, you are right that it does not seem to work properly at the moment. It works for C and C++, but not for most others. I've added a bug report for that https://github.com/gphalkes/t3highlight/issues/1, which I hopefully will get to soon.

**Comment by clhess** [comment] 2016-10-04 16:20
I've compiled in some minor changes already by adding some command line options for setting the line & column, i had to recompile some of the extra libraries to get this functionality though.  This has helped tremendously as I have a script file which searches my ctags file already and just calls the editor appropriately with the right filename, column, line.  So full ctag support as it would be nice to go to function declarations and definitions, is not a high priority.

I would like to see some column copy/paste functionality though.

**Comment by ulno** [comment] 2017-07-25 12:19
Are these changes (setting line and column) available anywhere?

**Comment by gphalkes** [comment] 2017-10-11 06:59
Emacs modeline support for highlighting was fixed in commit f1a88f7ff59323b1f92118487d91079fb1211f19

**Comment by gphalkes** [comment] 2017-10-22 12:17
Setting line and column from the command line when opening files has been implemented in commit d3f55eccf99584cc8055ede4355fbfa7d6ffaa0a

**Comment by clhess** [comment] 2017-10-23 04:38
So do you have a switch or know the modifications to the build environment in order to compile everything into the editor statically instead of using shared libs? Would make it easier for me to toss on a couple machines without having to install all the dependencies.

**Comment by gphalkes** [comment] 2017-10-25 07:11
I haven't tried static linking myself, but I guess it should work. Adding the -static flag to the LDFLAGS should probably do the trick, although I'm not 100% sure as I think I might have disabled the static library building.

**Comment by gphalkes** [comment] 2018-01-04 16:39
ruby support in libt3highlight is now available. https://github.com/gphalkes/t3highlight/commit/78135b370833e42a31f7e1d9b78197d6a1961a13

To summarize the other suggestions:
- more language modes: always nice, but it takes a lot of time to add one especially for languages that I don't use myself. Added ruby, and if anyone is interested, please provide language files for libt3highlight. (See https://os.ghalkes.nl/doc/libt3highlight/ for documentation.)
- fallback encoding: the current situation is that for files opened from the command line, the -e parameter can change the encoding. Otherwise UTF-8 is assumed. If anyone is interested, I could make the default configurable instead.
- Emacs mode lines for highlighting: bug fixed, so it should work now. For encodings is difficult as it requires re-loading the file if an alternate encoding is supposed to be loaded.
- multiline regex replace: won't implement. The internals of Tilde make this extremely hard to do correctly.
- add command line options to set the line & column to open a file at: implemented, just add :<line> or :<line>:<column> to the file name on the command prompt
- ctags support: this is a rather advanced feature, for which I don't have time to implement.
- static linking: haven't tried it, but should be possible except for the X11 clipboard integration module.  If there is a demand, then please open separate bug to discuss this.

That should be all the suggestions in this bug, with a resolution or reason why I won't be implementing it. Closing this bug now. Please file separate bugs if there are features I've missed.

**Closed by gphalkes** 2018-01-04 16:39 UTC

**Comment by cheapy** [comment] 2018-03-18 00:23
Could you add your command line enhancement to the --help screen?

Set the line & column to open a file at: implemented, just add : or :: to the file name

**Comment by gphalkes** [comment] 2018-03-18 10:13
Thanks for pointing out the oversight. I've updated the --help message and the manual page to include the new options and other interface changes

**Comment by cheapy** [comment] 2018-03-18 14:31
I'm working on figuring out how to configure Midnight Commander to use Tilde as its default external viewer and editor.  I'm hoping to use your new enhancement when it opens the files.

**Comment by cheapy** [comment] 2018-03-19 01:38
I figured it out.  It now goes to the line number in both F3/view and F4/edit modes when unselect internal viewer and editor and make the following mods:

in ~/.bashrc added:
# mc needs VIEWER or PAGER as well as EDITOR set in order to pass line number
VIEWER=tilde
EDITOR=tilde

in ~/.config/mc/ini added:
[External editor or viewer parameters]
tilde=%filename:%lineno

Needed to log out and back in for it to take effect
